<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EDSDKLib\EDSDKLib.csproj" />
  </ItemGroup>

</Project>
